"""Initial migration

Revision ID: 899af15a5fd2
Revises: 
Create Date: 2025-10-30 12:45:49.268026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899af15a5fd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

